/**
 * This file was automatically generated by VersionTag.cmake
 */
#pragma once
#define VCUpdateUtility_VERSION_MAJOR			0
#define VCUpdateUtility_VERSION_MINOR			0
#define VCUpdateUtility_VERSION_PATCH			0
#define VCUpdateUtility_VERSION_EXTRA			

// Current VCUpdateUtility version number as a string.
#define VCUpdateUtility_VERSION				"0.0.0"

// Current VCUpdateUtility extended version number as a string.
#define VCUpdateUtility_VERSION_EXTENDED		"0.0.0"
